version: '3.7'

services:
  engine:
    build: ./engine
    command: ./bin/start.sh
    env_file: ./engine/.env
    volumes:
      - ./engine:/src/github.com/gavr-games/reborn-mmorpg:cached
    ports:
      - 8080:8080
