version: '3.9'

services:
  caddy:
    image: abiosoft/caddy:0.11.5
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:cached
    ports:
      - 80:80

  api:
    build: ./api
    command: ./bin/start.sh
    env_file: .env
    volumes:
      - ./api:/usr/src/api
      - bundle-cache:/usr/local/bundle:cached
    ports:
      - 4567:4567
    depends_on:
      - db
    stdin_open: true
    tty: true

  engine:
    build: ./engine
    command: ./bin/start.sh
    env_file: .env
    volumes:
      - ./engine:/src/github.com/gavr-games/reborn-mmorpg:cached
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    command:
      - /bin/sh
      - '-c'
      - |
        yarn install
        yarn dev
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/frontend:cached
    ports:
      - 3000
    env_file: .env

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    env_file: .env
    ports:
      - 5432:5432

volumes:
  db-data: null
  bundle-cache: null
